### ISSUE TITLE
Update compound statement reference

### ISSUE THREAD

**Issue by dmoisset** [dmoisset/cpython#3]

**Comment by Fidget-Spinner** [comment]
In the spirit of keeping things smaller and easier for PR review, I made a branch of the `patma-docs` branch just for work on the language reference portion of the docs here https://github.com/dmoisset/cpython/tree/patma-docs-reference .  I have a hunch that our doc changes should be split into multiple smaller PRs when we make them against cpython so that the core devs have an easier time.

80% of it is copied from PEP 634. I had to restructure/reword some of it to fit how the language reference currently flows.

I'd really appreciate if you can take a brief look at it and tell me if things are generally fine :). No worries if you can't though - we can always wait till it's fully ready.

One possible bikeshedding point I'd like to get your opinion on: Should we used single quotes or double quotes for hard keywords in the grammar? 

The PEP [uses single quotes "by convention" for hard keywords](https://www.python.org/dev/peps/pep-0634/#appendix-a-full-grammar) and double quotes for soft keywords, whereas the [python language reference uses double quotes hard keywords](https://docs.python.org/3.10/reference/compound_stmts.html#the-for-statement). I'd like to follow the docs' style but that would make my grammar a tad different than the one in the PEP. Thoughts?

Thanks for your time and help in all of this!

**Comment by dmoisset** [comment]
Thanks! Can you creat a draft PR? that will make this easier to review

BTW, have you signed the Python Contributor License Agreement? (CLA). That will be useful by the time they want to merge our PR. See https://www.python.org/psf/contrib/contrib-form/ if you haven't

**Comment by Fidget-Spinner** [comment]
> Thanks! Can you creat a draft PR? that will make this easier to review


Give me a day or two. I'll make one when there's less TODOs lying around.

> BTW, have you signed the Python Contributor License Agreement? (CLA). That will be useful by the time they want to merge our PR. See https://www.python.org/psf/contrib/contrib-form/ if you haven't


Yeah!

**Comment by dmoisset** [comment]
It would be nice if you can create a draft PR even with the TODO sections, so I can start reviewing while you work

**Comment by Fidget-Spinner** [comment]
Sorry for the delay, it's at #6. It should be mostly done IMO.

**Comment by dmoisset** [comment]
This has been merged and I'm closing it, thanks again for the hard work. Note that I moved the work to branch patma-docs-rebase which is based in the latest (as of time of writing this) python/cpython:master rather than brandt's fork.

Feel free to comment in https://github.com/python/cpython/pull/24664 for updates or propose extra PRs to the branch if you can think of improvements to make. I'll do the same here to propose some changes in your reference docs that I'm still trying to organise.

A small additional note: I reverted one of your changes to use `object.__match_args__` instead of `class.__match_args__`. The datamodel reference only uses `class.X` for things that are useful in metaclasses rather than regular classes.

**Comment by Fidget-Spinner** [comment]
Alright. Thanks for clarifying!
